/// <reference types="next/image-types/global" />

// Committed on purpose: `next-env.d.ts` (which normally pulls these in) is generated by `next dev`/`next build` and
// is gitignored, so on a fresh checkout — CI's `tsc --noEmit` runs before any build — importing a `.webp` would
// otherwise fail to type-check.
