/**
 * Generates the committed files that turn source data into web code (D5, D8).
 *
 *   apps/web/src/generated/tokens.css       Tailwind theme, type and layer utilities, from @assembly/tokens
 *   apps/web/src/generated/brand-marks.tsx  server components for the approved wordmark and monogram SVGs
 *
 * Usage:
 *   node scripts/generate.mjs           write the files
 *   node scripts/generate.mjs --check   fail if a committed file is out of date (part of `pnpm check`)
 *
 * The token modules are leaf modules with no runtime imports, so Node loads them directly
 * (native type stripping). Output is formatted with the repo's Prettier config so it is stable.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import * as prettier from "prettier";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const TOKENS = path.join(ROOT, "packages/tokens/src");
const BRAND_SOURCE = path.join(ROOT, "docs/brand/source");
const OUT = path.join(ROOT, "apps/web/src/generated");
const CHECK = process.argv.includes("--check");

const HEADER =
  "GENERATED by scripts/generate.mjs. Do not edit: change the source and run `pnpm generate`.";

const load = (name) => import(pathToFileURL(path.join(TOKENS, `${name}.ts`)).href);
const kebab = (name) =>
  name.replace(/([a-z]{3,})(\d)/g, "$1-$2").replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const rem = (px) => `${+(px / 16).toFixed(4)}rem`;
const num = (value) => `${+value.toFixed(4)}`;

// ── tokens.css ───────────────────────────────────────────────────────────────

/** Font size for a type step: fluid steps interpolate across the viewport range, others switch at a breakpoint. */
function fontSize(step, fluidRange) {
  const [mobile, desktop] = step.size;
  if (mobile === desktop) return [`font-size: ${rem(mobile)};`];
  if (!step.fluid) {
    return [
      `font-size: ${rem(mobile)};`,
      `@media (min-width: 48rem) { font-size: ${rem(desktop)}; }`,
    ];
  }
  const slope = (desktop - mobile) / (fluidRange.max - fluidRange.min);
  const intercept = mobile - slope * fluidRange.min;
  return [
    `font-size: clamp(${rem(mobile)}, calc(${rem(intercept)} + ${num(slope * 100)}vw), ${rem(desktop)});`,
  ];
}

function typeUtility(name, step, { weight, fluidRange }) {
  const family = step.font === "sans" ? "var(--font-sans)" : "var(--font-mono)";
  const lines = [
    `font-family: ${family};`,
    ...fontSize(step, fluidRange),
    `line-height: ${step.leading};`,
    `font-weight: ${weight[step.weight]};`,
  ];
  if (step.width !== undefined && step.font === "sans") lines.push(`font-stretch: ${step.width}%;`);
  if (step.tracking !== undefined) lines.push(`letter-spacing: ${step.tracking}em;`);
  if (step.uppercase) lines.push("text-transform: uppercase;");
  return `@utility type-${kebab(name)} {\n${lines.map((l) => `  ${l}`).join("\n")}\n}`;
}

function hatchImage(hatch, ink) {
  // A stripe gradient runs perpendicular to its angle, so a line inclined `a` degrees uses (180 - a).
  return hatch.angles
    .map((a) => {
      const pitch = hatch.pitch;
      return `repeating-linear-gradient(${(180 - a) % 180}deg, ${ink} 0 1px, transparent 1px ${pitch}px)`;
    })
    .join(", ");
}

async function buildTokensCss() {
  const [{ color }, { layer }, { radius }, { shape }, typography, { motion }] = await Promise.all([
    load("color"),
    load("layer"),
    load("radius"),
    load("shape"),
    load("typography"),
    load("motion"),
  ]);
  const { font, typeScale } = typography;
  const px = (value) => `${value}px`;
  const ink = "var(--color-ink)";
  const shadowInk = `color-mix(in srgb, ${ink} ${shape.shadowOpacity * 100}%, transparent)`;

  const theme = [
    "--color-*: initial;",
    ...Object.entries(color).map(([name, hex]) => `--color-${kebab(name)}: ${hex};`),
    "--radius-*: initial;",
    ...Object.entries(radius).map(([name, value]) => `--radius-${name}: ${px(value)};`),
    "--shadow-*: initial;",
    ...Object.entries(shape.elevation).map(
      ([name, offset]) => `--shadow-cut-${name}: ${px(offset)} ${px(offset)} 0 0 ${shadowInk};`,
    ),
    "--ease-*: initial;",
    ...Object.entries(motion.ease).map(
      ([name, c]) => `--ease-${kebab(name)}: cubic-bezier(${c.join(", ")});`,
    ),
    ...Object.entries(motion.duration).map(([name, ms]) => `--duration-${name}: ${ms}ms;`),
    `--shape-stroke: ${px(shape.stroke)};`,
    `--shape-hairline: ${px(shape.hairline)};`,
    `--shape-grid-base: ${px(shape.grid.base)};`,
    `--shape-grid-iso: ${px(shape.grid.isoTile)};`,
    `--shape-grid-opacity: ${shape.grid.maxOpacity};`,
    `--shape-focus-inner: ${px(shape.focus.inner)};`,
    `--shape-focus-outer: ${px(shape.focus.outer)};`,
    `--shape-bezel: ${px(shape.device.bezel)};`,
    `--shape-screen-ratio: ${shape.device.screen.width} / ${shape.device.screen.height};`,
  ];

  // The font variables are set at runtime by next/font (--font-archivo, --font-jetbrains-mono),
  // so the stacks reference them: keep `variable` in apps/web/src/app/layout.tsx in step.
  const fontVar = (family) => `--font-${family.toLowerCase().replace(/\s+/g, "-")}`;
  const fonts = [
    "--font-*: initial;",
    ...Object.entries(font).map(
      ([name, f]) =>
        `--font-${name}: var(${fontVar(f.family)}), ${f.generic === "monospace" ? "ui-monospace, " : "system-ui, "}${f.generic};`,
    ),
  ];

  const paletteFills = Object.keys(color).map(
    (name) => `@utility p-${kebab(name)} {\n  fill: var(--color-${kebab(name)});\n}`,
  );

  const layers = Object.entries(layer).flatMap(([id, l]) => [
    `@utility layer-${id} {\n  background-color: var(--color-${kebab(l.fill)});\n  color: var(--color-${l.on});\n  border: var(--shape-stroke) solid ${ink};\n}`,
    `@utility hatch-${id} {\n  background-image: ${hatchImage(l.hatch, ink)};\n}`,
  ]);

  const types = Object.entries(typeScale).map(([name, step]) =>
    typeUtility(name, step, typography),
  );

  return [
    `/* ${HEADER} */`,
    `@theme static {\n${theme.map((l) => `  ${l}`).join("\n")}\n}`,
    `@theme static inline {\n${fonts.map((l) => `  ${l}`).join("\n")}\n}`,
    "/* Type scale: font, size, leading, weight, width and tracking together. */",
    ...types,
    "/* Palette fill classes, used by the generated SVG components. */",
    ...paletteFills,
    "/* Layer surfaces: fill, the one readable text colour, and the ink outline. Hatch goes on a strip, never behind text. */",
    ...layers,
    "/* Layer classes are built from a layer ID at runtime, so Tailwind cannot see them in the source. */",
    `@source inline("{layer,hatch}-{${Object.keys(layer).join(",")}}");`,
  ].join("\n\n");
}

// ── brand-marks.tsx ──────────────────────────────────────────────────────────

/** The approved marks (AG-9) and the component each becomes. */
const MARKS = [
  { name: "Wordmark", file: "br-02-wordmark-w-a.svg" },
  { name: "WordmarkReversed", file: "br-02-wordmark-w-a-reversed.svg" },
  { name: "Monogram", file: "br-03-monogram-m-b.svg" },
  { name: "MonogramReversed", file: "br-03-monogram-m-b-reversed.svg" },
];

const ATTR = /([\w:-]+)="([^"]*)"/g;
const attrs = (source) => Object.fromEntries([...source.matchAll(ATTR)].map((m) => [m[1], m[2]]));

function markComponent({ name, file }, svg) {
  const root = svg.match(/^<svg\s([^>]*)>(.*)<\/svg>\s*$/s);
  if (!root) throw new Error(`${file}: expected a single <svg> element`);
  const rootAttrs = attrs(root[1]);
  const paths = [...root[2].matchAll(/<path\s([^>]*?)\/>/g)];
  if (root[2].replace(/<path\s[^>]*?\/>/g, "").trim() !== "" || paths.length === 0) {
    throw new Error(`${file}: only <path> children are allowed by the SVG contract`);
  }
  for (const key of ["viewBox", "role", "aria-label"]) {
    if (!rootAttrs[key]) throw new Error(`${file}: missing ${key}`);
  }
  const children = paths.map(([, source]) => {
    const a = attrs(source);
    if (!a.class?.startsWith("p-") || !a.d)
      throw new Error(`${file}: every path needs a p-* class and d`);
    // The palette class supplies the fill, so the hex fallback is dropped. `id` becomes `data-part`,
    // because the same mark can appear twice on a page and IDs must stay unique.
    const props = [`data-part="${a.id}"`, `className="${a.class}"`];
    if (a["fill-rule"]) props.push(`fillRule="${a["fill-rule"]}"`);
    props.push(`d="${a.d}"`);
    return `<path ${props.join(" ")} />`;
  });
  return `export function ${name}({ className }: { className?: string }) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="${rootAttrs.viewBox}" role="img" aria-label="${rootAttrs["aria-label"]}" className={className}>
      ${children.join("\n      ")}
    </svg>
  );
}`;
}

async function buildBrandMarks() {
  const components = [];
  for (const mark of MARKS) {
    components.push(
      markComponent(mark, await readFile(path.join(BRAND_SOURCE, mark.file), "utf8")),
    );
  }
  return `/* ${HEADER} */\n\n${components.join("\n\n")}\n`;
}

// ── run ──────────────────────────────────────────────────────────────────────

async function format(file, text, parser) {
  const config = (await prettier.resolveConfig(file)) ?? {};
  return prettier.format(text, { ...config, parser });
}

const targets = [
  { file: path.join(OUT, "tokens.css"), build: buildTokensCss, parser: "css" },
  { file: path.join(OUT, "brand-marks.tsx"), build: buildBrandMarks, parser: "typescript" },
];

const stale = [];
for (const { file, build, parser } of targets) {
  const next = await format(file, await build(), parser);
  const current = await readFile(file, "utf8").catch(() => null);
  if (current === next) continue;
  if (CHECK) {
    stale.push(path.relative(ROOT, file));
  } else {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, next);
    console.log(`wrote ${path.relative(ROOT, file)}`);
  }
}

if (CHECK) {
  if (stale.length > 0) {
    console.error(`Out of date: ${stale.join(", ")}. Run \`pnpm generate\` and commit the result.`);
    process.exit(1);
  }
  console.log("✔ generated files are up to date");
}
